apiVersion: v1
name: glusterfs
description: |-
  glusterfs容器化集群。
  主机上面的映射目录固定为/var/lib/kubelet/glusterworkspace。
  每一个POD是stateful方式创建工作目录，也就是/var/lib/kubelet/glusterworkspace/glusterfs-n
  数据卷参数决定了创建多少个复制卷，每一个复制卷就是挂载卷名称。
  比如/var/lib/kubelet/glusterworkspace/glusterfs-0/volumes/sobeyvolume
  对应容器内目录为/glustervolumes/sobeyvolume
  因为PV插件的原因，目前只能使用hostnetwork模式，因此意味着一个主机上只会有一个POD

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.02020061604

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: gluster4u1_centos7

keywords:
  - glusterfs

maintainers:
  - email: wangxi@sobey.com
    name: wangxi
